language: php
php:
  - '7.0'

# From PHPUnit's config
install:
  - travis_retry composer install --no-interaction --prefer-source

script: ./vendor/bin/phpunit --coverage-text --whitelist src/ tests/
