name: Build and Test

on:
  push:
    branches:
      - master

  # Run tests for any PRs.
  pull_request:

env:
  CI: "true"
  # CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  # DOCKER_BUILDKIT: "1"

jobs:
  dependencies:
    runs-on: ubuntu-latest
    outputs:
      # Allow matrixing out the actual test steps
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    strategy:
      matrix:
        composer:
          # - low
          - high
        php:
          - 7.2
          - 7.3
          - 7.4
          - 8.0

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          coverage: xdebug
          php-version: ${{ matrix.php }}

      # TODO: build cache

      - name: Install dependencies
        run: composer install --no-interaction --no-ansi --no-progress --no-suggest --prefer-dist --optimize-autoloader
        # todo: prefer-lowest

      - name: PHPUnit
        run: vendor/bin/phpunit

  phpunit:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}

    steps:
      - name: PHPUnit
        run: vendor/bin/phpunit

  phpstan:
    runs-on: ubuntu-latest
    needs:
      - dependencies
    strategy:
      matrix: ${{fromJson(needs.job1.outputs.matrix)}}

    steps:
      - name: PHPUnit
        run: vendor/bin/phpstan

